### ISSUE TITLE
画布高度不断增加Bug

### ISSUE THREAD

**Issue by Luyuxuan1998** [cambridgejames/NodeEditor3-vue#1]
尊敬的NodeEditor3开发者，
我在使用您的NodeEditor3的最简单Demo的过程中发现了画布高度不断增加的Bug。

**Comment by cambridgejames** [comment]
您好，感谢您使用NodeEditor3组件，您的邮件我已收到。

如“快速开始”文档中所述，由于一些已知的原因，当前“[ne-panel组件、其父元素或其祖先元素中必须至少有一个元素拥有确定的宽度和高度，不能全都设置成100%，不然可能导致意料之外的问题](https://github.com/cambridgejames/NodeEditor3-vue/blob/cb4c6cf066499825d93a7779820e3b01a94b02e3/docs/guide/quick-start.md?plain=1#L57)”，因为`ne-panel`组件在运行时必须知道自己确切的高度。我注意到您在代码中使用了`width`和`height`属性来设置`div`盒子的宽度和高度：

![image](https://user-images.githubusercontent.com/42881533/235745505-b3a2d6da-900c-4d78-8363-4022cb17ec23.png)

根据MDN文档，`div`标签并没有`width`和`height`属性。因此，您通过上述方法为该标签设置的高度是无效的，因此`ne-panel`组件无法得知您设置的高度值，所以会引发您所遇到的问题。

相关MDN文档的链接如下：

1. [HTML全局属性 | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)
2. [div：内容划分元素 | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div)

您可以使用`style`或`class`属性来设置`div`元素的宽高。如：

```vue
<template>
    <div style="width: 800px; height: 600px;">
        <ne-panel :init="init"/>
    </div>
</template>
```

或

```vue
<template>
    <div class="my-class">
        <ne-panel :init="init"/>
    </div>
</template>
<style lang="scss" scope>
.my-class {
    width: 800px;
    height: 600px;
}
</style>
```
